component: nextjs # (必填) 组件名称，此处为nextjs
name: nextjsDemo # (必填) 实例名称
# org: hutao # (可选) 用于记录组织信息，默认为您的腾讯云账户 appid
app: htnext # (可选) 该 next.js 应用名称
# stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src: './src'
  functionName: nextjsDemo
  region: ap-guangzhou
  runtime: Nodejs10.15
  exclude:
    - .env
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
